[package]
name = "ricochet_board"
version = "0.1.0"
authors = ["Carl Scherer <dec@cscher.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
draw_a_box = { git = "https://github.com/Lireer/draw-a-box", branch = "main" }
rand_pcg = "0.3.0"
rand = "0.8.3"
